apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elsa-protoactor-repro.fullname" . }}
  labels:
    {{- include "elsa-protoactor-repro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "elsa-protoactor-repro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "elsa-protoactor-repro.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "elsa-protoactor-repro.serviceAccountName" . }}
      automountServiceAccountToken: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Minikube
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__Default
              valueFrom:
                secretKeyRef:
                  name: {{ include "elsa-protoactor-repro.fullname" . }}
                  key: connection-string
            - name: ProtoActor__ClusterName
              value: {{ include "elsa-protoactor-repro.clusterName" . | quote }}
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              path: /utils/hcheck/startup
              port: http
            {{- toYaml .Values.probes.startup | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /utils/hcheck/liveness
              port: http
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /utils/hcheck/readiness
              port: http
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
