apiVersion: v1
kind: Secret
metadata:
  name: {{ include "elsa-protoactor-repro.fullname" . }}
  labels:
    {{- include "elsa-protoactor-repro.labels" . | nindent 4 }}
type: Opaque
stringData:
  connection-string: {{ .Values.database.connectionString | quote }}
