<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elsa" Version="3.7.1" />
    <PackageReference Include="Elsa.Actors.ProtoActor" Version="3.7.1" />
    <PackageReference Include="Elsa.Caching.Distributed.ProtoActor" Version="3.7.1" />
    <PackageReference Include="Elsa.Persistence.EFCore.PostgreSql" Version="3.7.1" />
    <PackageReference Include="Elsa.Workflows.Api" Version="3.7.1" />
    <PackageReference Include="Elsa.Workflows.Runtime.ProtoActor" Version="3.7.1" />
    <PackageReference Include="Proto.Cluster.Dashboard" Version="1.8.0" />
    <PackageReference Include="Proto.Cluster.Kubernetes" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\.dockerignore">
      <Link>.dockerignore</Link>
    </Content>
  </ItemGroup>

</Project>
